(function(){'use strict';
var C={ArrowLeft:37,ArrowUp:38,ArrowRight:39,ArrowDown:40,Enter:13,Back:10009,Escape:27,ChannelUp:427,ChannelDown:428,MediaPlay:415,MediaPause:19,MediaPlayPause:10252,MediaStop:413,MediaRewind:412,MediaFastForward:417,MediaTrackPrevious:10232,MediaTrackNext:10233,ColorF0Red:403,ColorF1Green:404,ColorF2Yellow:405,ColorF3Blue:406};
var area='top',topIndex=1,sideIndex=0,channelIndex=0,modal=false,groups=[],channels=[],allChannels=[],group='__all',current=null,lastKey='',lastTime=0;
var $=function(id){return document.getElementById(id)};
function keyName(e){var n=Number(e.keyCode||e.which||0),k;for(k in C)if(C[k]===n)return k;var s=e.key||e.code||'';if(s==='Up')return'ArrowUp';if(s==='Down')return'ArrowDown';if(s==='Left')return'ArrowLeft';if(s==='Right')return'ArrowRight';if(s==='Return')return'Enter';if(s==='XF86Back')return'Back';if(s==='Escape')return'Back';return s}
function eat(e){try{e.preventDefault();e.stopPropagation();e.stopImmediatePropagation()}catch(_){} }
function diag(k,e){$('diagState').textContent='REMOTE ACTIVE';$('diagKey').textContent='LAST KEY: '+k+' ['+Number(e.keyCode||e.which||0)+']';clearTimeout(diag.t);diag.t=setTimeout(function(){$('diagState').textContent='REMOTE READY'},1600)}
function dedupe(k){var n=Date.now();if(k===lastKey&&n-lastTime<70)return true;lastKey=k;lastTime=n;return false}
function list(){return group==='__all'?allChannels:allChannels.filter(function(c){return c.group===group})}
function renderSidebar(){var a=$('sidebar'),h='<div class="side '+(area==='sidebar'&&sideIndex===0?'focused ':'')+(group==='__all'?'selected':'')+'"><span>All Channels</span><span>'+allChannels.length.toLocaleString()+'</span></div><div class="side '+(area==='sidebar'&&sideIndex===1?'focused ':'')+(group==='__fav'?'selected':'')+'"><span>Favourites</span><span>0</span></div>';groups.forEach(function(g,i){h+='<div class="side '+(area==='sidebar'&&sideIndex===i+2?'focused ':'')+(group===g?'selected':'')+'"><span>'+esc(g)+'</span></div>'});a.innerHTML=h}
function renderGrid(){var a=list(),g=$('grid');channels=a;$('count').textContent=a.length.toLocaleString()+' channels';g.innerHTML='';if(!a.length){g.innerHTML='<div class="empty">No playlist loaded. Press OK on SETTINGS.</div>';return}var start=Math.max(0,Math.floor(channelIndex/4)*4-8),end=Math.min(a.length,start+28);for(var i=start;i<end;i++){var c=a[i],d=document.createElement('div');d.className='channel'+(area==='channels'&&i===channelIndex?' focused':'');d.innerHTML=c.logo?'<img src="'+esc(c.logo)+'"><div><div class="name">'+esc(c.name)+'</div><div class="group">'+esc(c.group)+'</div></div>':'<div class="fallback">TV</div><div><div class="name">'+esc(c.name)+'</div><div class="group">'+esc(c.group)+'</div></div>';d.onclick=(function(ix){return function(){channelIndex=ix;area='channels';renderFocus();play()}})(i);g.appendChild(d)}}
function renderFocus(){document.querySelectorAll('.focused').forEach(function(x){x.classList.remove('focused')});var el=null;if(area==='top')el=topIndex?$('settings'):$('search');else if(area==='sidebar')el=document.querySelectorAll('.side')[sideIndex];else{var vis=document.querySelectorAll('.channel');el=vis.length?vis[channelIndex-Math.max(0,Math.floor(channelIndex/4)*4-8)]:null}if(el){el.classList.add('focused');try{el.scrollIntoView({block:'nearest',inline:'nearest'})}catch(_){}}$('diagSel').textContent='SELECTED: '+(area==='top'?(topIndex?'SETTINGS':'SEARCH'):area==='sidebar'?'SIDEBAR':'CHANNEL '+(channelIndex+1))}
function render(){renderSidebar();renderGrid();renderFocus()}
function play(){current=channels[channelIndex];if(current)$('playerText').textContent='▶ '+current.name}
function chooseSide(){var items=['__all','__fav'].concat(groups);group=items[Math.min(sideIndex,items.length-1)]||'__all';channelIndex=0;area='channels';render()}
function openModal(type){modal=true;var m=$('modal');m.classList.remove('hidden');if(type==='settings'){m.innerHTML='<div class="box"><h2>IPTV Settings</h2><input id="url" class="field" placeholder="M3U / M3U8 playlist URL"><button id="load" class="modalBtn">SAVE & LOAD</button><button id="cancel" class="modalBtn">CANCEL</button><div class="hint">Remote diagnostic stays visible. This build intentionally starts with the remote test layer so we can prove Samsung key delivery before adding more IPTV complexity.</div></div>';$('load').onclick=loadUrl;$('cancel').onclick=closeModal}else{m.innerHTML='<div class="box"><h2>Search</h2><input id="q" class="field" placeholder="Search channels"><button id="cancel" class="modalBtn">CANCEL</button></div>';$('q').oninput=search;$('cancel').onclick=closeModal;$('q').focus()}}
function closeModal(){modal=false;$('modal').classList.add('hidden');$('modal').innerHTML='';area='top';topIndex=1;renderFocus()}
function search(){var q=$('q').value.toLowerCase(),a=allChannels.filter(function(c){return c.name.toLowerCase().indexOf(q)>=0}).slice(0,30),box=$('modal').querySelector('.box');box.querySelectorAll('.result').forEach(function(x){x.remove()});a.reverse().forEach(function(c){var b=document.createElement('button');b.className='modalBtn result';b.textContent=c.name;b.onclick=function(){current=c;$('playerText').textContent='▶ '+c.name;closeModal()};box.insertBefore(b,box.querySelector('#cancel'))})}
function loadUrl(){var u=$('url').value.trim();if(!u)return;fetch(u,{cache:'no-store'}).then(function(r){return r.text()}).then(function(t){allChannels=parseM3U(t);groups=Array.from(new Set(allChannels.map(function(c){return c.group}))).sort();group='__all';channelIndex=0;closeModal();render()}).catch(function(e){$('playerText').textContent='Playlist error: '+e.message})}
function parseM3U(t){var out=[],meta=null;t.replace(/^\uFEFF/,'').split(/\r?\n/).forEach(function(line){line=line.trim();if(line.indexOf('#EXTINF:')===0){var p=line.indexOf(','),n=p>=0?line.slice(p+1).trim():'Channel',gm=line.match(/group-title="([^"]*)"/i),lm=line.match(/tvg-logo="([^"]*)"/i);meta={name:n,group:gm?gm[1]:'Uncategorised',logo:lm?lm[1]:''}}else if(line&&line.charAt(0)!=='#'&&meta){meta.url=line;out.push(meta);meta=null}});return out}
function moveModal(d){var els=[].slice.call(document.querySelectorAll('#modal button,#modal input'));if(!els.length)return;var i=els.indexOf(document.activeElement);i=Math.max(0,Math.min(els.length-1,i+d));els[i].focus();els.forEach(function(x,j){x.classList.toggle('focused',j===i)})}
function handle(e){var k=keyName(e);if(!k)return;diag(k,e);if(dedupe(k)){eat(e);return}if(modal){if(k==='Back'){closeModal();eat(e);return}if(k==='ArrowUp'||k==='ArrowDown'){moveModal(k==='ArrowUp'?-1:1);eat(e);return}if(k==='Enter'){if(document.activeElement&&document.activeElement.tagName==='BUTTON')document.activeElement.click();eat(e);return}return}if(k==='Back'){area=area==='sidebar'?'channels':'sidebar';renderFocus();eat(e);return}if(k==='ArrowLeft'){if(area==='top')topIndex=0;else if(area==='channels'&&channelIndex%4===0)area='sidebar';else if(area==='channels')channelIndex=Math.max(0,channelIndex-1);else area='top';renderFocus();eat(e);return}if(k==='ArrowRight'){if(area==='top')topIndex=1;else if(area==='sidebar')area='channels';else channelIndex=Math.min(Math.max(0,channels.length-1),channelIndex+1);renderFocus();eat(e);return}if(k==='ArrowUp'){if(area==='sidebar')sideIndex=Math.max(0,sideIndex-1);else if(area==='channels')channelIndex=Math.max(0,channelIndex-4);renderFocus();eat(e);return}if(k==='ArrowDown'){if(area==='top')area=channels.length?'channels':'sidebar';else if(area==='sidebar')sideIndex=Math.min(groups.length+1,sideIndex+1);else channelIndex=Math.min(Math.max(0,channels.length-1),channelIndex+4);renderFocus();eat(e);return}if(k==='Enter'){if(area==='top')openModal(topIndex?'settings':'search');else if(area==='sidebar')chooseSide();else play();eat(e);return}if(k==='ChannelUp'||k==='MediaTrackNext'){if(channels.length)channelIndex=(channelIndex+1)%channels.length;area='channels';renderFocus();play();eat(e);return}if(k==='ChannelDown'||k==='MediaTrackPrevious'){if(channels.length)channelIndex=(channelIndex-1+channels.length)%channels.length;area='channels';renderFocus();play();eat(e);return}}
$('search').onclick=function(){openModal('search')};$('settings').onclick=function(){openModal('settings')};
/* Samsung: Arrow/Enter/Back are mandatory and must not be registered. Use keydown. */
window.addEventListener('keydown',handle,true);document.addEventListener('keydown',handle,true);document.body.addEventListener('keydown',handle,true);
try{if(window.tizen&&tizen.tvinputdevice){tizen.tvinputdevice.registerKeyBatch(['MediaPlay','MediaPause','MediaPlayPause','MediaStop','MediaFastForward','MediaRewind','MediaTrackPrevious','MediaTrackNext','ColorF0Red','ColorF1Green','ColorF2Yellow','ColorF3Blue','ChannelUp','ChannelDown'])}}catch(_){try{['MediaPlay','MediaPause','MediaPlayPause','MediaStop','MediaFastForward','MediaRewind','MediaTrackPrevious','MediaTrackNext','ColorF0Red','ColorF1Green','ColorF2Yellow','ColorF3Blue','ChannelUp','ChannelDown'].forEach(function(k){try{tizen.tvinputdevice.registerKey(k)}catch(__){}})}catch(__){}}
render();
})();
